### ISSUE TITLE
Request: more distinctive WARNING lines

### ISSUE THREAD

**Issue by wilfwilson** [james-d-mitchell/gaplint#1]
In the Travis tests for Digraphs and Semigroups, we run various tests and tools, and then we use `grep` to search the output of these processes for certain keywords. At the end of its output, Travis displays the output of this `grep`. Thus, each failed line that it finds is printed. I find this useful.

Currently, when `gaplint` encounters a problem, it prints something like:
```
WARNING in gap/attr.gi:46   no space allowed before bracket  [1]
```
The problem with this is that the obvious failure keyword here is WARNING, and it's doesn't let me discriminate sufficiently. If I have WARNING as one of the keywords, then the Travis tests begin to fail because of innocuous warnings like:
```
#W WARNING: cannot find 'pdflatex', please install TeX.
```
It would be great if you update the warning to be something more distinctive, perhaps by including the word gaplint. eg:
```
gaplint: WARNING in gap/attr.gi:46   no space allowed before bracket  [1]
```
or something better. It's not a massive issue, since at the end of its search, gaplint prints FAILED if anything went wrong, and that's certainly something I can search for as a failure word. However, it doesn't give us the line-by-line list of every failure that is handy to have repeated at the end of the Travis file.

**Comment by james-d-mitchell** [comment]
I've played around with this a bit, the problem being, as I mentioned to you before, that prefixing the current message by "gaplint:" makes many of the messages too long. I've tried a number of different possible solutions to this, but I don't really like any of them. 

How about grepping for "WARNING gap" to detect problems with linting?

**Comment by wilfwilson** [comment]
Yes – I'll grep for "WARNING in". That resolves the issue as far as I'm concerned.
