### ISSUE TITLE
Add 'enabled' to enable a small set of lints

### ISSUE THREAD

**Issue by ChrisJefferson** [james-d-mitchell/gaplint#25]
For GAP core, we only use a small set of lints, and the list of 'disabled' lints has to be extended when new lints are added.

If you could give a list of enabled lints instead, that would mean new releases with new lints wouldn't break CI.

**Comment by james-d-mitchell** [comment]
Good suggestion @ChrisJefferson, I also thought of this, and even started implementing it yesterday. It seemed that adding this would make the logic surrounding what rules are suppressed where kind of complicated, and given that the alternative is quite straightforward I decided not to do it. It still could be done, I'm not against this, but I'm not sure that it's worth the effort to be honest.

**Comment by james-d-mitchell** [comment]
So, in the end I've come full circle and agree with you, and I've implemented this in #26, and will make an update to the GAP ci when I've merged the PR, and released a new version of gaplint @ChrisJefferson
