### ISSUE TITLE
pytest args are passed through to main()

### ISSUE THREAD

**Issue by orlitzky** [james-d-mitchell/gaplint#31]
When using pytest to run the test suite, any additional args passed to pytest wind up in `sys.argv`, and then `argparse` treats them as arguments to gaplint. For example,

```
$ pytest -vv
...
=========================== short test summary info ============================
FAILED tests/test_gaplint.py::TestScript::test_disable_global_rule - AssertionError: 'Aborting!' != 0
FAILED tests/test_gaplint.py::TestScript::test_wrong_ext - SystemExit: Aborting!
FAILED tests/test_gaplint.py::TestRules::test_run_gaplint - SystemExit: Aborting!
========================= 3 failed, 18 passed in 0.72s =========================
```

Each of those is complaining about the unknown argument `-vv`:

```
gaplint.py:1110: SystemExit
----------------------------- Captured stderr call -----------------------------
Unknown command line option: ['-vv']
```

One potential fix for this is to wipe `sys.argv` in `main()` if it was called from... elsewhere:

```python
def main(**kwargs) -> None:
    if __name__ != "__main__":
        sys.argv = []
    args = _parse_args(kwargs)
```

I ran in to this on Gentoo where the package manager runs pytest with a crazy string of arguments.

**Comment by james-d-mitchell** [comment]
Thanks for the report @orlitzky, will attempt to fix this asap.

**Comment by james-d-mitchell** [comment]
Resolved in v1.2.0

**Comment by orlitzky** [comment]
Thanks for the quick fix (for this and the other two issues), but I'm embarrassed to say that I've caused a new problem. The console_scripts magic in https://github.com/james-d-mitchell/gaplint/blob/main/setup.py#L27 generates a wrapper for `gaplint.py` that looks like,


```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from gaplint import main
if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
```

When that wrapper is executed, the `__name__` inside of `gaplint.py` is no longer `__main__` -- it's `gaplint`! So in that case, my clever workaround erases argv and is not so clever after all.

I'll think about this for a bit before suggesting anything else.

**Comment by orlitzky** [comment]
Oh, I see you already discovered that and fixed it properly. Thanks again & sorry for the headache. Everything works great now, I've added v1.2.1 to Gentoo: https://github.com/gentoo/gentoo/commit/f962363558ed5f82c7d2b758e01cf7ab67299108
